- name: Install packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - build-essential
    - make
    - git
    - libssl-dev

- name: Clone wrk2
  git: repo=https://github.com/giltene/wrk2.git dest=/root/wrk2 depth=1

- name: Make wrk2
  command: make chdir=/root/wrk2 creates=/root/wrk2/wrk

